### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by GreenAA** [megadose/toutatis#100]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\777da\AppData\Local\Programs\Python\Python311\Scripts\toutatis.exe\__main__.py", line 7, in <module>
  File "C:\Users\777da\AppData\Local\Programs\Python\Python311\Lib\site-packages\toutatis\core.py", line 85, in main
    if not infos["user"]:
           ~~~~~^^^^^^^^
KeyError: 'user'

**Comment by mauljurassicia** [comment]
I dont have a solutions but i know the reason. In the source code btw because this package just really small package you can read it by your self there is a function that return two different map scheme based on whether request succesful or not. This is not really good practice, they creature shouldve use more proper error handling.  I assume instagram disallow or maybe deprecating the api that this osint tools use. So yeah if that the case maybe there are no workarounds to use this packeage

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
