### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by JacouilleLaFripouille** [megadose/toutatis#103]
I have this issue:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.10/dist-packages/toutatis-1.26-py3.10.egg/toutatis/core.py", line 84, in main
  File "/usr/local/lib/python3.10/dist-packages/toutatis-1.26-py3.10.egg/toutatis/core.py", line 32, in getInfo
  File "/usr/local/lib/python3.10/dist-packages/toutatis-1.26-py3.10.egg/toutatis/core.py", line 25, in getUserId
  File "/usr/lib/python3/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

Anyone can help me ?

**Comment by lee-har** [comment]
I had a similar issue to you, and I fixed it. Try this:
`sudo pip uninstall toutatis`
`rm -rf toutatis`
`git clone https://github.com/programerr01/toutatis.git`
`cd toutatis'
`sudo python3 setup.py install`
`cd toutatis`
`toutatis -u <username> -s <sessionid>`

**Comment by PradeepVarma-81** [comment]
Still it is not working... If it is really working.. then please help

**Comment by Roohnoor** [comment]
> I had a similar issue to you, and I fixed it. Try this: `sudo pip uninstall toutatis` `rm -rf toutatis` `git clone https://github.com/programerr01/toutatis.git` `cd toutatis` `sudo python3 setup.py install` `cd toutatis` `toutatis -u USERNAME -s SESSIONID`

![Screenshot_2024-05-30_15-56-37](https://github.com/megadose/toutatis/assets/144744866/c4fad542-b77c-438c-8d34-1dd79895ade9)
now tell me what to do

**Comment by lee-har** [comment]
@Roohnoor You haven't built the dependencies correctly. I just tested this on a python3.11 virtual environment running toutatis1.26. Works fine for me.
![image](https://github.com/megadose/toutatis/assets/95121701/67276b93-c06f-46a9-9240-eb359edd28ad)
