### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wesamlibya** [megadose/toutatis#106]
How can I fix this error :

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/toutatis-1.26-py3.11.egg/toutatis/core.py", line 82, in main
  File "/usr/local/lib/python3.11/dist-packages/toutatis-1.26-py3.11.egg/toutatis/core.py", line 30, in getInfo
  File "/usr/local/lib/python3.11/dist-packages/toutatis-1.26-py3.11.egg/toutatis/core.py", line 23, in getUserId
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

<img width="746" alt="يييسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسسس" src="https://github.com/megadose/toutatis/assets/95371893/af0440a5-3d7b-4ab8-a980-d8e9106fefb4">

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
