### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MDsoso74** [megadose/toutatis#111]
i everyone,

i can't run toutatis because of this:

Traceback (most recent call last):
  File "/usr/bin/venv/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.31', 'console_scripts', 'toutatis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/venv/lib/python3.11/site-packages/toutatis-1.31-py3.11.egg/toutatis/core.py", line 84, in main
KeyError: 'user'

I verified my version is the 1.31. I've have very few  python knowledge, if somebody can help me to fix it?

**Comment by Chaython** [comment]
Im not sure, but the key 'user' should be username of whos data you want to pull for example to pull me
Be sure to replace instagramsessionid with your actual session ID also, as shown in the readme
toutatis -u classychay -s instagramsessionid
