### ISSUE TITLE
issue full_name 

### ISSUE THREAD

**Issue by EmiruFeet** [megadose/toutatis#121]
so i keep running into this issue anytime i look a profile up i get this error                                        Traceback (most recent call last):
  File "/home/user/venv/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.31', 'console_scripts', 'toutatis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/toutatis/core.py", line 91, in main
    print("Full Name              : "+infos["full_name"])
                                      ~~~~~^^^^^^^^^^^^^
any help would be appreciated im kinda new to linux

**Comment by lahadiyani** [comment]
Check API Response

**Comment by 0xNiru** [comment]
try with this command -> `toutatis -u TARGET_USERNAME -s YOUR_SESSIONID`
