### ISSUE TITLE
getting following errors

### ISSUE THREAD

**Issue by niemajak900** [megadose/toutatis#25]
toutatis -u usernameexample  -s instagramsessionid                                                                                                          
Informations about     : usernameexample
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.25', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 87, in main
KeyError: 'full_name'

after I did apt update I got this one now:

Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.25', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 80, in main
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 32, in getInfo
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by niemajak900** [comment]
![screen](https://user-images.githubusercontent.com/82961814/156812682-14e25412-be86-4a06-a115-16015dcf5234.jpg)

I am making everything correctly don't know why I got this error

**Comment by niemajak900** [comment]
fixed.
