### ISSUE TITLE
Traceback Help

### ISSUE THREAD

**Issue by slaishxd** [megadose/toutatis#29]
```
┌──(root㉿DESKTOP-x)-[/home/xx/toutatis]
└─# toutatis -u (user) -s (ID)
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.25', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 80, in main
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 32, in getInfo
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I don't know how to fix it. What should I do?
```

**Comment by novitae** [comment]
the pip version is not actualized, try with the new one like this
```
pip uninstall toutatis
y
git clone https://github.com/megadose/toutatis/
cd toutatis
pip install .
```
