### ISSUE TITLE
helppp

### ISSUE THREAD

**Issue by Biggitybaked** [megadose/toutatis#31]
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/toutatis/core.py", line 80, in main
    infos = getInfo(args.username,sessionsId)
  File "/usr/local/lib/python3.9/dist-packages/toutatis/core.py", line 32, in getInfo
    info = json.loads(response.text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

any ideas?

**Comment by novitae** [comment]
the pip version is not actualized, try with the new one like this
```
pip uninstall toutatis
y
git clone https://github.com/megadose/toutatis/
cd toutatis
pip install .
```

**Comment by Biggitybaked** [comment]
Damn, you got back to me quick, i wish everyone on github was even half that responsive. I appreciate that. 👌👍 Thank you.

And thank you for explaining that about the script to me. I new to linux and python and didnt know that. More on the graphics\front end\windows side of the fence. Its been intereting learning Linux thats forsure.

Ill give it a go here in a little bit and let ya know how it goes.
Wish me luck. 😂
Thanks again!
- BB




________________________________
