### ISSUE TITLE
Cannot use toutatis

### ISSUE THREAD

**Issue by Rizvaan** [megadose/toutatis#39]
Hi, when I want to use the tool I have this error and I can't how to fix it. . .

I don't saw any issues about my problem : 

`Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.26-py3.9.egg/toutatis/core.py", line 84, in main
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.26-py3.9.egg/toutatis/core.py", line 32, in getInfo
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.26-py3.9.egg/toutatis/core.py", line 25, in getUserId
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

![image](https://user-images.githubusercontent.com/106781859/177059892-457465c8-f2c9-48eb-a412-0674d95f8778.png)

Thanks to any response to fix it !

**Comment by atz-spe** [comment]
There's a problem with Instagram request parameters since ~1 month.
See : https://github.com/megadose/toutatis/pull/40
