### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by aftaabhussain** [megadose/toutatis#47]

**Comment by aftaabhussain** [comment]
when i try to use it i ge this error
ModuleNotFoundError: No module named 'requests'

C:\Users\Faheemah>toutatis -u nibha_rai03 -s 30897059273%3AOCPavRbeYpCbea%3A1%3AAYeIeSCFgSuHz7UO5tNaumEhkkv1-K554eg_Hac1Gg
Traceback (most recent call last):
  File "c:\users\faheemah\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\faheemah\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Faheemah\AppData\Local\Programs\Python\Python38-32\Scripts\toutatis.exe\__main__.py", line 4, in <module>
  File "c:\users\faheemah\appdata\local\programs\python\python38-32\lib\site-packages\toutatis\__init__.py", line 1, in <module>
    from toutatis.core import *
  File "c:\users\faheemah\appdata\local\programs\python\python38-32\lib\site-packages\toutatis\core.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by megadose** [comment]
pip install requests
