### ISSUE TITLE
No module named 'requests' (your are doing an incredible work !)

### ISSUE THREAD

**Issue by JFGTX** [megadose/toutatis#58]
On execution:

Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\toutatis.exe\__main__.py", line 4, in <module>
  File "D:\Python\lib\site-packages\toutatis\__init__.py", line 1, in <module>
    from toutatis.core import *
  File "D:\Python\lib\site-packages\toutatis\core.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by megadose** [comment]
pip install requests
