### ISSUE TITLE
Error full name

### ISSUE THREAD

**Issue by Max6468** [megadose/toutatis#67]
why i have this error?

Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.10/dist-packages/toutatis-1.26-py3.10.egg/toutatis/core.py", line 92, in main
KeyError: 'full_name'

**Comment by Max6468** [comment]
the user id was wront
