### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TensorMx** [megadose/toutatis#9]
I have a problem
┌──(root💀kali)-[/home/kali/toutatis]
└─# toutatis --username staryuuki --sessionid 5939829932                                                                               1 ⨯
Informations about     : staryuuki
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.25', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.25-py3.9.egg/toutatis/core.py", line 87, in main
KeyError: 'full_name'

**Comment by TensorMx** [comment]
Ya lo resolvi gracias
